name: Java CI with Maven on feature

on:
    push:
        branches:
            - 'feat_**'
            - 'main'

jobs:
 build:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Test with Maven
          run: mvn test 